simulation:
  data_num: 1000 #一つのデータセットのデータ数
  data_set_num: 8 #作成するデータセットの数(測定におけるコース数)
  l: 30 # 多重波の数
  delta_d: 0.005 #サンプル間隔[m]
  c: 3e8  # 光速 [m/s]
  f: 1.298e9  # キャリア周波数 [Hz]
  r: 1  # 反射波の振幅
  k_rice: 4 
  predicted_dataset_num: 3 # RMSEを出すときにいくつのデータセットを予測して平均値を出すか

model:
  rnn_type: SimpleRNN 
  optimizer_type: AdamW
  in_features: 1 #入力特徴量の数(入力するデータが何種類あるか)
  input_len: 50
  hidden_nums: [20]
  out_steps_num: 1 #何点予測するか
  batch_size: 256
  epochs: 100
  learning_rate: 0.0005
  patience: 5

save:
  recursive_num: 500 #再帰予測で予測する回数(現状使ってない)
  plot_start: 0 #予測結果のグラフの表示スタート開始位置
  plot_range: 200 #グラフとして表示する範囲

  use_mlflow: true #mlflowを使うかどうか(mlflowが使えない環境ではFalseを指定)
  experiment_name: test-2

  base_dir: exp_runs #mlflowを使わないときの保存フォルダ名

