simulation:
  data_num: 800 #一つのデータセットのデータ数
  data_set_num: 8 #作成するデータセットの数(測定におけるコース数)
  l: 30 # 多重波の数(直接波+反射波の数)
  delta_d: 0.03925 #サンプル間隔[m]
  c: 3e8  # 光速 [m/s]
  f: 1.298e9  # キャリア周波数 [Hz]
  target_k_db: 4 #目標とするライスファクタ
  predicted_dataset_num: 1 # RMSEを出すときにいくつのデータセットを予測して平均値を出すか

model:
  rnn_type: SimpleRNN 
  optimizer_type: Adam
  in_features: 1 #入力特徴量の数(入力するデータが何種類あるか)
  input_len: 50
  hidden_nums: [10]
  out_steps_num: 5 #何点予測するか
  batch_size: 128
  epochs: 10
  learning_rate: 0.001
  patience: 2

save:
  recursive_num: 500 #再帰予測で予測する回数(現状使ってない)
  plot_start: 0 #予測結果のグラフの表示スタート開始位置
  plot_range: 60 #グラフとして表示する範囲

  use_mlflow: true #mlflowを使うかどうか(mlflowが使えない環境ではFalseを指定)
  experiment_name: test-v2

  base_dir: exp_runs #mlflowを使わないときの保存フォルダ名

