measure:
  train_cources: [1,2,4]
  val_cources: [3,17]
  predict_cource: 9 #予測したいコース番号
  start_ratio: 0 
  end_ratio: 1
  data_axis: time
  
model:
  rnn_type: SimpleRNN 
  optimizer_type: Adam 
  in_features: 1 #入力特徴量の数(入力するデータが何種類あるか)
  input_len: 100
  hidden_nums: [20]
  out_steps_num: 1 #何点予測するか
  batch_size: 128
  epochs: 100
  learning_rate: 0.001
  patience: 5

save:
  recursive_num: 500 #再帰予測で予測する回数(現状使ってない)
  plot_start: 0 #予測結果のグラフの表示スタート開始位置
  plot_range: 200 #グラフとして表示する範囲

  use_mlflow: true #mlflowを使うかどうか(mlflowが使えない環境ではFalseを指定)
  experiment_name: test

  base_dir: exp_runs #mlflowを使わないときの保存フォルダ名

