n_jobs: 2 # いくつ並列処理させるか

params: 
  measure:
    cource:
      - train: [1,2,4,5,6,7,8,10,11,12,13,14,15,16]
        val: [3,17]
        predict: 9
  model:
    rnn_type: [SimpleRNN]
    optimizer: [Adam]
    input_len: [25,50]
    hidden_nums: 
      - [20]
      - [64,32]
    out_steps_num: [1]
    batch_size: [128]
    learning_rate: [0.0003,0.0002,0.0005,0.001]